services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EonX\ScheduleBundle\Command\ScheduleRunCommand: ~

    EonX\ScheduleBundle\DataCollector\ScheduleDataCollector:
        tags:
            -
                name: data_collector
                template: '@Schedule/Collector/schedule_collector.html.twig'
                id: !php/const EonX\ScheduleBundle\DataCollector\ScheduleDataCollector::NAME

    EonX\ScheduleBundle\Interfaces\ScheduleInterface:
        class: EonX\ScheduleBundle\Schedule

    EonX\ScheduleBundle\Interfaces\ScheduleRunnerInterface:
        class: EonX\ScheduleBundle\ScheduleRunner
